apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/manifests.yaml
- bases/webhook-certificate.yaml
- bases/service.yaml

transformers:
- transformers/webhook-nameprefix-transformer.yaml

patches:
- path: patches/webhook-patch.yaml