apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "accesserator-system/webhook-cert"
webhooks:
  - name: mpod-v1.kb.io
    clientConfig:
      service:
        name: webhook-service
        namespace: accesserator-system
    namespaceSelector:
      matchExpressions:
        - key: accesserator-webhooks
          operator: In
          values:
            - enabled
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "accesserator-system/webhook-cert"
webhooks:
  - name: vpod-v1.kb.io
    clientConfig:
      service:
        name: webhook-service
        namespace: accesserator-system
    namespaceSelector:
      matchExpressions:
        - key: accesserator-webhooks
          operator: In
          values:
            - enabled