apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: accesserator-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "accesserator-system/webhook-cert"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      url : https://host.docker.internal:9443/mutate--v1-pod
    failurePolicy: Fail
    name: mpod-v1.kb.io
    namespaceSelector:
      matchExpressions:
        - key: accesserator-webhooks
          operator: In
          values:
            - enabled
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: accesserator-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "accesserator-system/webhook-cert"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://host.docker.internal:9443/validate--v1-pod
    name: vpod-v1.kb.io
    namespaceSelector:
      matchExpressions:
        - key: accesserator-webhooks
          operator: In
          values:
            - enabled
    failurePolicy: Fail
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None