apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: accesserator
  name: webhook-cert
  namespace: accesserator-system
spec:
  dnsNames:
    - host.docker.internal
  issuerRef:
    kind: Issuer
    name: webhook-selfsigned
  secretName: webhook-server-cert